# name: publish-pypi

# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   pypi:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: packaging/python
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.x'

#       - name: Inject version from tag
#         run: |
#           TAG=${GITHUB_REF_NAME}
#           V=${TAG#v}
#           sed -i "s/__version__ = \"0.0.0\"/__version__ = \"$V\"/" src/tnr_installer/__init__.py

#       - name: Build
#         run: |
#           python -m pip install --upgrade pip build
#           python -m build

#       - name: Publish to PyPI
#         uses: pypa/gh-action-pypi-publish@v1.12.2
#         with:
#           user: __token__
#           password: ${{ secrets.PYPI_API_TOKEN }}


